base_url: https://openspot-dinamis.data-terra.org/api/geo/YEAR_SOURCE
api_url: https://openspot-dinamis.data-terra.org/api/lien_tif
cookie: eyJ2YWx1ZXMiOls1NDIzXX0.ZwlFpQ.m0BvNR2D6ujHt3NnVCDy7gjsLqY # If expired, to obtain the cookie, fill in the required form by hand and collect it from storage once this has been done
years: [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

save_dir: /lustre/fsn1/projects/rech/ego/commun/fajwel/spot_raw
